"use client";
import { useRouter, useSearchParams } from "next/navigation";
import { useActiveOrders } from "@/lib/query/use-active-orders";
import { readOperationsFilters, writeOperationsFilters } from "@/lib/query/operations-search-params";
import { OperationsShell } from "@/components/layout/operations-shell";
import { OrderFilters } from "@/components/orders/order-filters";
import { OrderList } from "@/components/orders/order-list";

export function OrdersView() {
  const router = useRouter(); const params = useSearchParams(); const filters = readOperationsFilters(params); const query = useActiveOrders(filters);
  const update = (next: Partial<typeof filters>) => { const merged = { ...filters, ...next }; router.push(`/orders?${writeOperationsFilters({ ...merged, page: next.city || next.status ? 1 : merged.page })}`); };
  return <OperationsShell><section className="mx-auto max-w-7xl px-5 py-8 sm:px-8 lg:px-12 lg:py-12"><header className="mb-8 flex flex-wrap items-end justify-between gap-4"><div><p className="mb-3 font-mono text-[10px] uppercase tracking-[.22em] text-[var(--slate-500)]">01 / Operaciones en vivo</p><h1 className="display-face text-4xl tracking-tight sm:text-5xl">Pedidos en riesgo</h1><p className="mt-3 max-w-xl text-sm leading-6 text-[var(--slate-500)]">La cola de decisión para el turno. Ordenada por prioridad operativa, no por hora de llegada.</p></div><div className="border-l-2 border-[var(--amber-500)] pl-4 text-sm"><p className="font-mono text-2xl">{query.data?.pagination.total ?? "—"}</p><p className="text-xs text-[var(--slate-500)]">pedidos activos</p></div></header><OrderFilters city={filters.city} status={filters.status} onCity={(city) => update({ city })} onStatus={(status) => update({ status })} onRefresh={() => void query.refetch()} refreshing={query.isFetching} /><div aria-live="polite" className="py-4 text-xs text-[var(--slate-500)]">{query.isFetching ? "Actualizando prioridad…" : query.data ? `Página ${query.data.pagination.page} de ${query.data.pagination.totalPages}` : ""}</div>{query.isPending ? <div className="border-y border-[var(--paper-200)] py-20 text-center text-sm text-[var(--slate-500)]">Cargando la cola operacional…</div> : query.isError ? <div role="alert" className="border border-[var(--red-500)]/40 bg-white p-6 text-sm">No pudimos cargar los pedidos. <button className="ml-2 font-bold underline" onClick={() => void query.refetch()}>Intentar de nuevo</button></div> : query.data?.data.length === 0 ? <div className="border-y border-[var(--paper-200)] py-20 text-center"><p className="display-face text-2xl">Sin pedidos para estos filtros</p><p className="mt-2 text-sm text-[var(--slate-500)]">Prueba otra ciudad o estado.</p></div> : <OrderList orders={query.data?.data ?? []} />}<nav aria-label="Paginación de pedidos" className="flex justify-between border-b border-[var(--paper-200)] py-5"><button type="button" disabled={filters.page <= 1 || query.isFetching} onClick={() => update({ page: filters.page - 1 })} className="min-h-10 px-3 text-sm underline disabled:no-underline disabled:opacity-30">← Anterior</button><button type="button" disabled={!query.data || filters.page >= query.data.pagination.totalPages || query.isFetching} onClick={() => update({ page: filters.page + 1 })} className="min-h-10 px-3 text-sm underline disabled:no-underline disabled:opacity-30">Siguiente →</button></nav></section></OperationsShell>;
}
